// <auto-generated />
using System;
using CommonObjectLibraryCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommonObjectLibraryCore.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20210827174643_Update1")]
    partial class Update1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommonObjectLibraryCore.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaseReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.CaseEntity", b =>
                {
                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.HasKey("CaseId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("CaseEntities");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.Entity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityTypeId")
                        .HasColumnType("int");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityTypeId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.EntityType", b =>
                {
                    b.Property<int>("EntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityTypeId");

                    b.ToTable("EntityTypes");

                    b.HasData(
                        new
                        {
                            EntityTypeId = 1,
                            EntityTypeName = "Borrower"
                        },
                        new
                        {
                            EntityTypeId = 2,
                            EntityTypeName = "Solicitor"
                        },
                        new
                        {
                            EntityTypeId = 3,
                            EntityTypeName = "Client"
                        });
                });

            modelBuilder.Entity("CommonObjectLibraryCore.CaseEntity", b =>
                {
                    b.HasOne("CommonObjectLibraryCore.Case", "Case")
                        .WithMany("CaseEntities")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonObjectLibraryCore.Entity", "Entity")
                        .WithMany("CaseEntities")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.Entity", b =>
                {
                    b.HasOne("CommonObjectLibraryCore.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId");

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.Case", b =>
                {
                    b.Navigation("CaseEntities");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.Entity", b =>
                {
                    b.Navigation("CaseEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
