// <auto-generated />
using System;
using CommonObjectLibraryCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommonObjectLibraryCore.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20210828161704_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommonObjectLibraryCore.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaseReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CaseId");

                    b.HasIndex("CaseReference")
                        .IsUnique();

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.CaseEntity", b =>
                {
                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CaseEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("CompanyEntityEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntityRoleId")
                        .HasColumnType("int");

                    b.Property<Guid?>("IndividualEntityEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CaseId", "EntityId");

                    b.HasIndex("CompanyEntityEntityId");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityRoleId");

                    b.HasIndex("IndividualEntityEntityId");

                    b.ToTable("CaseEntities");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.CaseEntityDataPoint", b =>
                {
                    b.Property<int>("CaseEntityDataPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CaseEntityCaseId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CaseEntityEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DataPointTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DataPointValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseEntityDataPointId");

                    b.HasIndex("DataPointTypeId");

                    b.HasIndex("CaseEntityCaseId", "CaseEntityEntityId");

                    b.ToTable("CaseEntityDataPoints");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.DataPointType", b =>
                {
                    b.Property<int>("DataPointTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataPointName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataPointTypeId");

                    b.ToTable("DataPointTypes");

                    b.HasData(
                        new
                        {
                            DataPointTypeId = 1,
                            DataPointName = "Reference"
                        });
                });

            modelBuilder.Entity("CommonObjectLibraryCore.Entity", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrincipalAddressPostalAddressId")
                        .HasColumnType("int");

                    b.HasKey("EntityId");

                    b.HasIndex("PrincipalAddressPostalAddressId");

                    b.ToTable("Entities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Entity");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.EntityRole", b =>
                {
                    b.Property<int>("EntityRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntityRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EntityRoleId");

                    b.HasIndex("EntityRoleName")
                        .IsUnique();

                    b.ToTable("EntityRoles");

                    b.HasData(
                        new
                        {
                            EntityRoleId = 1,
                            EntityRoleName = "Borrower"
                        },
                        new
                        {
                            EntityRoleId = 2,
                            EntityRoleName = "Solicitor"
                        },
                        new
                        {
                            EntityRoleId = 3,
                            EntityRoleName = "Client"
                        },
                        new
                        {
                            EntityRoleId = 4,
                            EntityRoleName = "Case Handler"
                        });
                });

            modelBuilder.Entity("CommonObjectLibraryCore.PostalAddress", b =>
                {
                    b.Property<int>("PostalAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostalAddressId");

                    b.ToTable("PostalAddresses");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.CompanyEntity", b =>
                {
                    b.HasBaseType("CommonObjectLibraryCore.Entity");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CompanyEntity");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.IndividualEntity", b =>
                {
                    b.HasBaseType("CommonObjectLibraryCore.Entity");

                    b.Property<string>("FirstNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("IndividualEntity");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.CaseEntity", b =>
                {
                    b.HasOne("CommonObjectLibraryCore.Case", "Case")
                        .WithMany("CaseEntities")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonObjectLibraryCore.CompanyEntity", null)
                        .WithMany("CaseEntities")
                        .HasForeignKey("CompanyEntityEntityId");

                    b.HasOne("CommonObjectLibraryCore.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonObjectLibraryCore.EntityRole", "EntityRole")
                        .WithMany()
                        .HasForeignKey("EntityRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonObjectLibraryCore.IndividualEntity", null)
                        .WithMany("CaseEntities")
                        .HasForeignKey("IndividualEntityEntityId");

                    b.Navigation("Case");

                    b.Navigation("Entity");

                    b.Navigation("EntityRole");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.CaseEntityDataPoint", b =>
                {
                    b.HasOne("CommonObjectLibraryCore.DataPointType", "DataPointType")
                        .WithMany()
                        .HasForeignKey("DataPointTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonObjectLibraryCore.CaseEntity", null)
                        .WithMany("CaseEntityDataPointList")
                        .HasForeignKey("CaseEntityCaseId", "CaseEntityEntityId");

                    b.Navigation("DataPointType");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.Entity", b =>
                {
                    b.HasOne("CommonObjectLibraryCore.PostalAddress", "PrincipalAddress")
                        .WithMany()
                        .HasForeignKey("PrincipalAddressPostalAddressId");

                    b.Navigation("PrincipalAddress");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.Case", b =>
                {
                    b.Navigation("CaseEntities");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.CaseEntity", b =>
                {
                    b.Navigation("CaseEntityDataPointList");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.CompanyEntity", b =>
                {
                    b.Navigation("CaseEntities");
                });

            modelBuilder.Entity("CommonObjectLibraryCore.IndividualEntity", b =>
                {
                    b.Navigation("CaseEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
